; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

define i333 @test1(i333 %X) {
; CHECK-LABEL: @test1(
; CHECK-NEXT:    [[Y:%.*]] = lshr i333 [[X:%.*]], 46
; CHECK-NEXT:    ret i333 [[Y]]
;
  %Y = udiv i333 %X, 70368744177664
  ret i333 %Y
}

define i499 @test2(i499 %X) {
; CHECK-LABEL: @test2(
; CHECK-NEXT:    [[Y:%.*]] = lshr i499 [[X:%.*]], 209
; CHECK-NEXT:    ret i499 [[Y]]
;
  %tmp.0 = shl i499 4096, 197
  %Y = udiv i499 %X, %tmp.0
  ret i499 %Y
}

define i599 @test3(i599 %X, i1 %C) {
; CHECK-LABEL: @test3(
; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[C:%.*]], i599 46, i599 12, !prof [[PROF0:![0-9]+]]
; CHECK-NEXT:    [[R:%.*]] = lshr i599 [[X:%.*]], [[TMP1]]
; CHECK-NEXT:    ret i599 [[R]]
;
  %V = select i1 %C, i599 70368744177664, i599 4096, !prof !0
  %R = udiv i599 %X, %V
  ret i599 %R
}

!0 = !{!"branch_weights", i32 3, i32 4}
;.
; CHECK: [[PROF0]] = !{!"branch_weights", i32 3, i32 4}
;.
