; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

define i33 @test1(i33 %X) {
; CHECK-LABEL: @test1(
; CHECK-NEXT:    [[Y:%.*]] = lshr i33 [[X:%.*]], 12
; CHECK-NEXT:    ret i33 [[Y]]
;
  %Y = udiv i33 %X, 4096
  ret i33 %Y
}

define i49 @test2(i49 %X) {
; CHECK-LABEL: @test2(
; CHECK-NEXT:    [[Y:%.*]] = lshr i49 [[X:%.*]], 29
; CHECK-NEXT:    ret i49 [[Y]]
;
  %tmp.0 = shl i49 4096, 17
  %Y = udiv i49 %X, %tmp.0
  ret i49 %Y
}

define i59 @test3(i59 %X, i1 %C) {
; CHECK-LABEL: @test3(
; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[C:%.*]], i59 10, i59 12, !prof [[PROF0:![0-9]+]]
; CHECK-NEXT:    [[R:%.*]] = lshr i59 [[X:%.*]], [[TMP1]]
; CHECK-NEXT:    ret i59 [[R]]
;
  %V = select i1 %C, i59 1024, i59 4096, !prof !0
  %R = udiv i59 %X, %V
  ret i59 %R
}

!0 = !{!"branch_weights", i32 1, i32 2}
;.
; CHECK: [[PROF0]] = !{!"branch_weights", i32 1, i32 2}
;.
